### ISSUE TITLE
Missing dependency on package.json

### ISSUE THREAD

**Issue by nolddor** [jfsiii/set-function-name#1]
Error: Cannot find module 'functions-have-names'
Require stack:
- /home/nolddor/gems-steam-bot/node_modules/set-function-name/index.js

**Comment by chenhui5416** [comment]
+1

**Comment by greguz** [comment]
+1

**Comment by micreas** [comment]
+1

**Comment by AmirHussain93** [comment]
+1

**Comment by AmirHussain93** [comment]
+1

**Comment by rus-tech-ae** [comment]
+1

**Comment by snapeuh** [comment]
Same problem, package is a dependency of Quill and can't build my app.

**Comment by madpilot78** [comment]
As a quick workaround you can just run `npm i -D functions-have-names` (or equivalent yarn command).

In this way the dependency is fulfilled locally.

**Comment by snapeuh** [comment]
Yes, we did the same on our project.

**Comment by lihqi** [comment]
1

**Comment by timhuebner** [comment]
+1

**Comment by OverPa1n** [comment]
+1 broke production release flow

**Comment by IhorShmidt** [comment]
+1

**Comment by tiparega** [comment]
> As a quick workaround you can just run `npm i -D functions-have-names` (or equivalent yarn command).
> 
> In this way the dependency is fulfilled locally.

@madpilot78 I tried and didn't work for me, I don't know too much about npm. It allows me to install a tool (cdktf) that uses this, but when I try to run it says it doens't found the module. Do I need to do another thing?

```
npm i -D functions-have-names
npm install --global cdktf-cli@latest
cdktf get --language java #Fails
```

**Comment by madpilot78** [comment]
> > As a quick workaround you can just run `npm i -D functions-have-names` (or equivalent yarn command).
> > In this way the dependency is fulfilled locally.
> 
> @madpilot78 I tried and didn't work for me, I don't know too much about npm. It allows me to install a tool (cdktf) that uses this, but when I try to run it says it doens't found the module. Do I need to do another thing?
> 
> ```
> npm i -D functions-have-names
> npm install --global cdktf-cli@latest
> cdktf get --language java #Fails
> ```

@tiparega 

Yours is a completely different situation. You're installing your tool with the `--global` npm flag, so you should also install `functions-have-names` using `--global`, I guess. But yours is a different situation and I cannot be sure it will be solved this easily.

So, try with --global, but I'm not sure this can fix it in your use case. You'd better ask the cdktf people though.

**Comment by tiparega** [comment]
It worked! Thank you!

**Comment by sneridagh** [comment]
@ljharb man, this is breaking a lot of builds that use `@testing-library/cypress` and `@testing-library/dom` Could you please issue a patch asap?

**Comment by ndelangen** [comment]
This is the commit that broke things:
https://github.com/ljharb/set-function-name/commit/f5e4771266c95567d87f6dc2cff94c986bc7e074

**Comment by micreas** [comment]
> @ljharb man, this is breaking a lot of builds that use `@testing-library/cypress` and `@testing-library/dom` Could you please issue a patch asap?

He is sleeping. Its 4:40 AM at his location. I bet he merged it and went to sleep without testing it much :smile:

**Comment by ljharb** [comment]
@micreas i tested it plenty; all of the places I'm using it already had functions-have-names in node_modules, so I didn't notice this.

I was indeed sleeping; v2.0.1 is now published, which should fix this issue.

For everyone freaking out overnight, don't you people use lockfiles?

**Comment by kenkku** [comment]
> For everyone freaking out overnight, don't you people use lockfiles?

At least some people (including me) were affected when installing CLI tools, such as `cdktf-cli`, with `npm i --global`. A good learning experience though, not a good idea to install tools from npm without a lockfile!

**Comment by ljharb** [comment]
Indeed, virtually nothing should be globally installed :-) CLI tools should be in package.json and invoked with npx.

**Comment by ndelangen** [comment]
Thank you @ljharb it's greatly appreciated.
Sorry you had a rough morning. ❤️

**Comment by jmustonen** [comment]
> For everyone freaking out overnight, don't you people use lockfiles?

For us, this was somewhat deep dependency chain: `pdfkit` -> `fontkit` -> `deep-equal` -> `regexp.prototype.flags` -- not sure why our lockfile didn't help there though 🤔 

But oh well, anyway, thanks for the quick fix ❤️

**Comment by akx** [comment]
FWIW, [eslint-plugin-import has a `no-extraneous-dependencies` rule](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md) that catches dev deps being used at runtime.

**Comment by ljharb** [comment]
@akx yes, thanks, i'm aware since i'm the maintainer for eslint-plugin-import. i haven't included it in my shared config yet because eslint v8.9 broke parsing for my use case, and I can't update.

**Comment by micreas** [comment]
> @micreas i tested it plenty; all of the places I'm using it already had functions-have-names in node_modules, so I didn't notice this.
> 
> I was indeed sleeping; v2.0.1 is now published, which should fix this issue.
> 
> For everyone freaking out overnight, don't you people use lockfiles?

We have a monorepo setup that uses Lerna. We have one lockfile for the monorepo that works locally but for production, the services are being deployed individually without a lockfile because Lerna does not generate individual lockfiles for each service/package. We found out about it when our services started failing in production after deployment because the module was missing and our instances could not start.
