### ISSUE TITLE
No matching version found for set-function-name@^2.0.1.

### ISSUE THREAD

**Issue by suleymanakilli** [jfsiii/set-function-name#5]
After version 2.0.1 we are getting "No matching version found for set-function-name@^2.0.1" when we try npm install. We tried npm clean cache --force but didn't help. 
npm view set-function-name versions -> ['1.0.0', '2.0.0']
npm version -> v6.14.12
node version -> v10.24.1

Full error:
```
10885 verbose node v10.24.1
10886 verbose npm  v6.14.12
10887 error code ETARGET
10888 error notarget No matching version found for set-function-name@^2.0.1.
10889 error notarget In most cases you or one of your dependencies are requesting
10889 error notarget a package version that doesn't exist.
10889 error notarget
10889 error notarget It was specified as a dependency of 'promise.prototype.finally'
10890 verbose exit [ 1, true ]
```

**Comment by thefoxes86** [comment]
Hi I have the same problem. Do you think that could be a npm cache problem ?
I wait for a response from the developers

Thanks

**Comment by thefoxes86** [comment]
I solved with `npm cache clean --force`

**Comment by ljharb** [comment]
This suggests that your private registry needs updating.
